import { Fields } from './types'

export const wordsPerMinute = 225
export const defaultExposedWordCounterFieldId = 'word_counter'

export const fieldsOptions = [
  { label: 'String fields', value: Fields.stringField },
  { label: 'Text fields', value: Fields.textField },
  { label: 'Structured text fields', value: Fields.structuredTextField },
]

export const calculationsConstants = {
  numberOfCharacters: '1',
  numberOfSpecialCharacters: '2',
  numberOfSentences: '3',
  numberOfParagraphs: '4',
  showCommonWords: '5',
  readingTime: '6',
}

export const calculationsOptions = [
  {
    label: 'Number of characters',
    value: calculationsConstants.numberOfCharacters,
  },
  {
    label: 'Number of special characters',
    value: calculationsConstants.numberOfSpecialCharacters,
  },
  {
    label: 'Number of sentences',
    value: calculationsConstants.numberOfSentences,
  },
  {
    label: 'Number of paragraphs',
    value: calculationsConstants.numberOfParagraphs,
  },
  { label: 'Reading time', value: calculationsConstants.readingTime },
  { label: 'Show common words', value: calculationsConstants.showCommonWords },
]

export const spaceConstants = {
  showSwitch: '1',
  includeSpaces: '2',
  excludeSpaces: '3',
}

export const spaceOptions = [
  { label: 'Show switch to toggle spaces', value: spaceConstants.showSwitch },
  { label: 'Always include spaces', value: spaceConstants.includeSpaces },
  { label: 'Never include spaces', value: spaceConstants.excludeSpaces },
]

export const htmlConstants = {
  showSwitch: '1',
  includeHTML: '2',
  excludeHTML: '3',
}

export const htmlOptions = [
  { label: 'Show switch to toggle HTML', value: htmlConstants.showSwitch },
  { label: 'Always include HTML elements', value: htmlConstants.includeHTML },
  { label: 'Never include HTML elements', value: htmlConstants.excludeHTML },
]

export const htmlElements = [
  'a',
  'abbr',
  'acronym',
  'address',
  'applet',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'base',
  'basefont',
  'bdi',
  'bdo',
  'bgsound',
  'big',
  'blink',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'center',
  'cite',
  'code',
  'col',
  'colgroup',
  'content',
  'data',
  'datalist',
  'dd',
  'decorator',
  'del',
  'details',
  'dfn',
  'dir',
  'div',
  'dl',
  'dt',
  'element',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'font',
  'footer',
  'form',
  'frame',
  'frameset',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'isindex',
  'kbd',
  'keygen',
  'label',
  'legend',
  'li',
  'link',
  'listing',
  'main',
  'map',
  'mark',
  'marquee',
  'menu',
  'menuitem',
  'meta',
  'meter',
  'nav',
  'nobr',
  'noframes',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'param',
  'plaintext',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'script',
  'section',
  'select',
  'shadow',
  'small',
  'source',
  'spacer',
  'span',
  'strike',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'template',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'tt',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
  'xmp',
]
